name: changuito_demo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.7
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.5
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.2.0
  google_sign_in: ^6.1.4
  http: ^0.13.6
  path_provider: ^2.1.2
  pdfx: ^2.4.0
  google_mlkit_text_recognition: ^0.8.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  google_mlkit_commons:
    path: lib_overrides/google_mlkit_commons
  google_mlkit_text_recognition:
    path: lib_overrides/google_mlkit_text_recognition
